
working_directory: "/scratch/omegacam_work_dir"

credentials:
  user: "fredericdux"
  program_id: "114.27U3.001"



reduced_format: perccd

####################### reduction report
# path to save the HTML report
report_path: "/www/people/dux/public/VST_p3/reduction_status.html"


# directory containing the reduced data
reduced_data_dir: "/projects/astro/cosmograil/PRERED/VST/reduced/"

# list of objects to consider
objects:
  - "eRASS1 J0501-0733"

already_plate_solved: false  # 2024-11-26: scamp-ing upstream everything to ensure compatibility.


####################### mosaic

discovery_file_pattern: "OMEGA.*FCS.fits"

mosaic_working_directory: /scratch/omegacam_work_dir/mosaic/ #/projects/astro/cosmograil/PRERED/VST/mosaic

directories:
  - /scratch/omegacam_work_dir/reduced/eRASS1_J0501-0733
#  - /projects/astro/cosmograil/PRERED/VST/reduced/J0722-3901_wide_field
#  - /projects/astro/cosmograil/PRERED/VST/reduced/COOL_J0542-2125_wide_field
#  - /projects/astro/cosmograil/PRERED/VST/reduced/eRASS1_J0501-0733_wide_field

database:
  name: omegacam_data.db  # will be at mosaic_working_directory

logging:
  level: INFO
  file: omegacam_mosaic.log

ccd_masks_directory: /scratch/omegacam_work_dir/ccd_masks #/projects/astro/cosmograil/PRERED/VST/ccd_masks

# paths to SCAMP and SExtractor binaries
scamp_bin: "/usr/bin/scamp"
sex_bin: "/usr/bin/sex"
swarp_bin: "/usr/bin/swarp"

# where we save the sources (it is expensive to run sextractor, so we will first check there.)
sources_save_dir: "/tmp/sources"
# same for headers produced by scamp
headers_save_dir: "/tmp/headers"

# (temporary) working directory
tmp_dir: "/scratch/tmp_omegacam"
# whether to keep the temporary directory after processing
keep_tmp: true

